# Supervised Learning Model Evaluation Lab

Complete the exercises below to solidify your knowledge and understanding of supervised learning model evaluation.

In [1]:
import pandas as pd

from sklearn.ensemble import RandomForestRegressor as rfr
from sklearn.model_selection import train_test_split as tts


In [2]:
%pip install scikit-learn==1.1.3


import pandas as pd
import numpy as np


Note: you may need to restart the kernel to use updated packages.


## Regression Model Evaluation

In [3]:
from sklearn.datasets import load_boston  # Dentro del módulo de sklearn importa un dataset con info de viviendas en Boston

import warnings
warnings.filterwarnings('ignore')

data = load_boston()

'''Con este conjunto de datos, tengo características y una variable objetivo para predecir. 
Voy a crear X que contendrá un df con las características'''

X = pd.DataFrame(data["data"], columns=data["feature_names"])

'''También creo Y, que contiene la variable a predecir en numérico, MEDV significa que representa 
el valor mediano'''

y = pd.DataFrame(data["target"], columns=['MEDV'])

'''Con concat los uno(concateno)'''

data = pd.concat([X, y], axis=1)

## 1. Split this data set into training (80%) and testing (20%) sets.

The `MEDV` field represents the median value of owner-occupied homes (in $1000's) and is the target variable that we will want to predict.

In [4]:
'''Ahora voy a dividir los datos en conjuntos: utilizando train_test_split (tts). 
con test_size estoy creando un parámetro para tener un 20% para prueba y un 80% para entrenamiento.'''

X_train, X_test, y_train, y_test = tts(X, y, test_size = 0.2)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((404, 13), (102, 13), (404, 1), (102, 1))

## 2. Train a `LinearRegression` model on this data set and generate predictions on both the training and the testing set.

In [5]:
from sklearn.metrics import confusion_matrix as cm
from sklearn.linear_model import LinearRegression as LinReg

'''Utilizo el modelo de regresión lineal con mis datos de entrenamiento. Son los datos que va a aprender para
hacer las predicciones'''

lreg = LinReg()
lreg.fit(X_train, y_train)

lreg

LinearRegression()

In [6]:
'''Aquí muestro las 5 primeras predicciones de la prueba y el entrenamiento'''

yp_test = lreg.predict(X_test)
yp_train = lreg.predict(X_train)

yp_test[:5], yp_train[:5]

(array([[-5.82218439],
        [19.99985537],
        [13.16536694],
        [13.56857433],
        [36.89551116]]),
 array([[20.83073963],
        [ 6.12440968],
        [26.98145013],
        [29.39767286],
        [24.59930613]]))

## 3. Calculate and print R-squared for both the training and the testing set.

In [7]:
from sklearn.metrics import r2_score as r2

'''La R2 del entrenamiento y del test'''

r2test = r2(y_test, yp_test)
r2train = r2(y_train, yp_train)

r2test, r2train

(0.7013983117335175, 0.7429286097554365)

## 4. Calculate and print mean squared error for both the training and the testing set.

In [8]:
from sklearn.metrics import mean_squared_error as mse 

mse_test = mse(y_test, yp_test)
mse_train = mse(y_train, yp_train)

mse_test, mse_train

(22.190650475046425, 22.100710233135246)

## 5. Calculate and print mean absolute error for both the training and the testing set.

In [9]:
from sklearn.metrics import mean_absolute_error as mae

mae_test = mae(y_test, yp_test)
mae_train = mae(y_train, yp_train)

mae_test, mae_train

(3.276070661739392, 3.3377563409407127)

## Classification Model Evaluation

In [10]:
from sklearn.datasets import load_iris

''''''

data = load_iris()

X = pd.DataFrame(data["data"], columns=data["feature_names"])
y = pd.DataFrame(data["target"], columns=["class"])

data = pd.concat([X, y], axis=1)

In [11]:
data.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   class  
0      0  
1      0  
2      0  
3      0  
4      0

## 6. Split this data set into training (80%) and testing (20%) sets.

The `class` field represents the type of flower and is the target variable that we will want to predict.

In [12]:
'''Ahora voy a dividir los datos en conjuntos: utilizando train_test_split (tts). 
con test_size estoy creando un parámetro para tener un 20% para prueba y un 80% para entrenamiento.'''

X_train, X_test, y_train, y_test = tts(X, y, test_size = 0.2)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((120, 4), (30, 4), (120, 1), (30, 1))

## 7. Train a `LogisticRegression` model on this data set and generate predictions on both the training and the testing set.

In [25]:
from sklearn.linear_model import LogisticRegression

# Separo los datos en características y variable objetivo

X = data.drop("class", axis=1)
y = data["class"]

# Divido los datos en entrenamiento y prueba

X_train, X_test, y_train, y_test = tts(X, y, test_size=0.2, random_state=0)

# Creo una instancia del modelo de Regresión Logística

logreg = LogisticRegression()

# Entreno el modelo utilizando los datos de entrenamiento

logreg.fit(X_train, y_train)

# Predicciones de la prueba

y_train_pred = logreg.predict(X_train)

y_test_pred = logreg.predict(X_test)


y_test_pred

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0])

## 8. Calculate and print the accuracy score for both the training and the testing set.

In [26]:
from sklearn.metrics import accuracy_score

train_accuracy = accuracy_score(y_train, y_train_pred)

test_accuracy = accuracy_score(y_test, y_test_pred)

print(train_accuracy)

print(test_accuracy)

0.9666666666666667
1.0


## 9. Calculate and print the balanced accuracy score for both the training and the testing set.

In [27]:
from sklearn.metrics import balanced_accuracy_score

# Calcular e imprimir la puntuación de precisión balanceada en el conjunto de entrenamiento
train_balanced_accuracy = balanced_accuracy_score(y_train, y_train_pred)
print("Precisión Balanceada en Entrenamiento:", train_balanced_accuracy)

# Calcular e imprimir la puntuación de precisión balanceada en el conjunto de prueba
test_balanced_accuracy = balanced_accuracy_score(y_test, y_test_pred)
print("Precisión Balanceada en Prueba:", test_balanced_accuracy)

Precisión Balanceada en Entrenamiento: 0.9653972153972153
Precisión Balanceada en Prueba: 1.0


## 10. Calculate and print the precision score for both the training and the testing set.

In [30]:
from sklearn.metrics import precision_score

# Calcular e imprimir la puntuación de precisión para el conjunto de entrenamiento
train_precision = precision_score(y_train, y_train_pred, average='weighted')
print("Precisión en entrenamiento:", train_precision)

# Calcular e imprimir la puntuación de precisión para el conjunto de prueba
test_precision = precision_score(y_test, y_test_pred, average='weighted')
print("Precisión en prueba:", test_precision)

Precisión en entrenamiento: 0.9672774327122153
Precisión en prueba: 1.0


## 11. Calculate and print the recall score for both the training and the testing set.

In [32]:
from sklearn.metrics import recall_score

# Calcular e imprimir el recall en el conjunto de entrenamiento
train_recall = recall_score(y_train, y_train_pred, average='weighted')
print("Recall en entrenamiento:", train_recall)

# Calcular e imprimir el recall en el conjunto de prueba
test_recall = recall_score(y_test, y_test_pred, average='weighted')
print("Recall en prueba:", test_recall)

Recall en entrenamiento: 0.9666666666666667
Recall en prueba: 1.0


## 12. Calculate and print the F1 score for both the training and the testing set.

In [33]:
'''Es la media armónica entre la precisión y el recall, 
proporciona una medida equilibrada del rendimiento del clasificador que tiene en cuenta tanto los falsos 
positivos como los falsos negativos'''

from sklearn.metrics import f1_score

# Calcular e imprimir el puntaje F1 para el conjunto de entrenamiento
train_f1 = f1_score(y_train, y_train_pred, average='weighted')
print("Puntaje F1 en entrenamiento:", train_f1)

# Calcular e imprimir el puntaje F1 para el conjunto de prueba
test_f1 = f1_score(y_test, y_test_pred, average='weighted')
print("Puntaje F1 en prueba:", test_f1)

Puntaje F1 en entrenamiento: 0.9665740740740743
Puntaje F1 en prueba: 1.0


## 13. Generate confusion matrices for both the training and the testing set.

In [ ]:
'''La matriz de confusión muestra la cantidad de ejemplos clasificados correctos e incorrectos para cada clase'''


In [34]:
from sklearn.metrics import confusion_matrix

# Generar la matriz de confusión para el conjunto de entrenamiento
train_cm = confusion_matrix(y_train, y_train_pred)
print("Matriz de confusión en entrenamiento:")
print(train_cm)

# Generar la matriz de confusión para el conjunto de prueba
test_cm = confusion_matrix(y_test, y_test_pred)
print("Matriz de confusión en prueba:")
print(test_cm)

Matriz de confusión en entrenamiento:
[[39  0  0]
 [ 0 34  3]
 [ 0  1 43]]
Matriz de confusión en prueba:
[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]


## Bonus: For each of the data sets in this lab, try training with some of the other models you have learned about, recalculate the evaluation metrics, and compare to determine which models perform best on each data set.

In [36]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn import svm
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Entrenar y evaluar diferentes modelos en el conjunto de entrenamiento y prueba

# Modelo de Regresión Logística
logreg = LogisticRegression()
logreg.fit(X_train, y_train)
logreg_train_pred = logreg.predict(X_train)
logreg_test_pred = logreg.predict(X_test)
logreg_accuracy = accuracy_score(y_test, logreg_test_pred)
logreg_precision = precision_score(y_test, logreg_test_pred, average='macro')
logreg_recall = recall_score(y_test, logreg_test_pred)
logreg_f1 = f1_score(y_test, logreg_test_pred)
logreg_cm = confusion_matrix(y_test, logreg_test_pred)

# Modelo de Árbol de Decisión
decision_tree = DecisionTreeClassifier()
decision_tree.fit(X_train, y_train)
decision_tree_train_pred = decision_tree.predict(X_train)
decision_tree_test_pred = decision_tree.predict(X_test)
decision_tree_accuracy = accuracy_score(y_test, decision_tree_test_pred)
decision_tree_precision = precision_score(y_test, decision_tree_test_pred)
decision_tree_recall = recall_score(y_test, decision_tree_test_pred)
decision_tree_f1 = f1_score(y_test, decision_tree_test_pred)
decision_tree_cm = confusion_matrix(y_test, decision_tree_test_pred)

# Modelo de Random Forest
random_forest = RandomForestClassifier()
random_forest.fit(X_train, y_train)
random_forest_train_pred = random_forest.predict(X_train)
random_forest_test_pred = random_forest.predict(X_test)
random_forest_accuracy = accuracy_score(y_test, random_forest_test_pred)
random_forest_precision = precision_score(y_test, random_forest_test_pred)
random_forest_recall = recall_score(y_test, random_forest_test_pred)
random_forest_f1 = f1_score(y_test, random_forest_test_pred)
random_forest_cm = confusion_matrix(y_test, random_forest_test_pred)

# Modelo de Naive Bayes
naive_bayes = GaussianNB()
naive_bayes.fit(X_train, y_train)
naive_bayes_train_pred = naive_bayes.predict(X_train)
naive_bayes_test_pred = naive_bayes.predict(X_test)
naive_bayes_accuracy = accuracy_score(y_test, naive_bayes_test_pred)
naive_bayes_precision = precision_score(y_test, naive_bayes_test_pred)
naive_bayes_recall = recall_score(y_test, naive_bayes_test_pred)
naive_bayes_f1 = f1_score(y_test, naive_bayes_test_pred)
naive_bayes_cm = confusion_matrix(y_test, naive_bayes_test_pred)

# Modelo de SVM
support_vector_machine = svm.SVC()
support_vector_machine.fit(X_train, y_train)
svm_train_pred = support_vector_machine.predict(X_train)
svm_test_pred = support_vector_machine.predict(X_test)
svm_accuracy = accuracy_score(y_test, svm_test_pred)
svm_precision = precision_score(y_test, svm_test_pred)
svm_recall = recall_score(y_test, svm_test_pred)
svm_f1 = f1_score(y_test, svm_test_pred)
svm_cm = confusion_matrix(y_test, svm_test_pred)

# Imprimir las métricas de evaluación para cada modelo
print("Modelo de Regresión Logística:")
print("Accuracy:", logreg_accuracy)
print("Precision:", logreg_precision)
print("Recall:", logreg_recall)
print("F1-score:", logreg_f1)
print("Confusion Matrix:")
print(logreg_cm)


ValueError: Target is multiclass but average='binary'. Please choose another average setting, one of [None, 'micro', 'macro', 'weighted'].